{% set name = "tacs" %}
{% set version = "0.1" %}
{% set build = 0 %}

{% set mpi = mpi or 'openmpi' %}
{% if scalar == "real" %}
{% set build = build + 100 %}
{% endif %}

package:
  name: "tacs"
  version: "{{ version }}"

source:
  git_url: https://github.com/timryanb/tacs.git

build:
  number: {{ build }} 
  string: py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ build }}_{{ scalar }}
  track_features:
    - tacs_complex  # [scalar == "complex"]

requirements:
  build:
    - python
    - numpy   1.18   # [py==37]
    - numpy   1.18   # [py==38]
    - numpy   1.19   # [py==39]
    - numpy   1.22   # [py==310]
    - {{ mpi }}
    - {{ compiler('cxx') }}
    - make
    - mpi4py
    - cython
    - setuptools

  host:
    - python
    - pip
    - numpy   1.18   # [py==37]
    - numpy   1.18   # [py==38]
    - numpy   1.19   # [py==39]
    - numpy   1.22   # [py==310]
    - {{ mpi }}
    - libopenblas
    - lapack
    - metis >=5.1
    - mpi4py
    - cython
    - setuptools

  run:
    - python >=3.7
    - numpy >=1.18.5,<2.0.a0   # [py==37]
    - numpy >=1.18.5,<2.0.a0   # [py==38]
    - numpy >=1.19.5,<2.0.a0   # [py==39]
    - numpy >=1.22.0,<2.0.a0   # [py==310]
    - scipy
    - {{ mpi }}
    - libopenblas
    - lapack
    - metis >=5.1
    - mpi4py
    - pynastran

test:
  requires:
    - testflo

  source_files:
    - tests

  commands:
    - export OMPI_MCA_btl=self,tcp
    - export OMPI_MCA_rmaps_base_oversubscribe=1
    #- testflo --timeout 120 tests/

about:
  home: https://github.com/smdogroup/tacs
  license: APACHE
  license_family: APACHE
  summary: Parallel finite-element analysis package
